name: so_pysm_models

channels:
    - astropy
    - conda-forge

dependencies:
    - python>=3.6
    - astropy
    - numba
    - toml
    - Cython
    - matplotlib
    - numpy
    - scipy==1.2.1
    - pip
    - sphinx-astropy
    - healpy
    - pip:
        - https://github.com/healpy/pysm/archive/master.zip
